project:
  type: website
  output-dir: docs


website:
  title: Statistical Analysis of Metagenomic Data
  site-url: ""
  favicon: img/logo_univ_nantes_simple.png
  navbar:
    background: light
    title: Statistical Analysis of Metagenomic Data
    logo: images/lille_logo.png
    logo-href: https://www.univ-lille.fr/
    left:
      - icon: file-earmark-font-fill
        text: Feuille de TP
        href: TP_StatGdeDim.pdf
        
    right:
      - href: https://clement-poupelin.github.io/Blog_template/
        text: Home
      - about.qmd
      - icon: github
        menu: 
          - href: https://github.com/Clement-Poupelin
            text: Clément Poupelin
          - href: https://github.com/nonomtrt
            text: Noémie Matrat
      - icon: linkedin
        menu: 
          - href: https://www.linkedin.com/in/ines-bakli-513b1126b/
            text: Ines Bakli
          - href: https://www.linkedin.com/in/pl49000/
            text: Paul Lemonnier
      - icon: envelope
        href: mailto:clementjc.poupelin@gmail.com
      - icon: person-circle
        href: http://clement-poupelin.github.io/

  page-footer: 
    background: light
    left: Copyright 2026, name here
    right: This blog is built with [Quarto](https://quarto.org/)


format:

  html:
    theme: 
      light: flatly
      dark: darkly
    css: custom.css
    toc: true

    
editor: visual