{
  "hash": "a48ae4d8198588b8875b0b315451e480",
  "result": {
    "engine": "knitr",
    "markdown": "---\n  title: \"1: Data preparation\"\n  format: \n    html: \n      theme: cosmo\n      toc: true\n      code-fold: true\n      code-summary: \"Show code\"\n      code-tools: true\n  editor: visual\n  categories: [\"Preparatory Analysis\"]\n  image: \"/img/dataPrep.png\"\n  description: \"Preparatory work for Statistical Analysis of Metagenomic Data\"\n---\n\n\n\n\n\n# Introduction\n\nBefore performing metagenomic analyses, it is important to explore and clean the dataset. This step includes:\n\n-   importing OTU, taxonomy, and metadata tables,\n-   creating a phyloseq object,\n-   checking for missing values,\n-   verifying sequencing depth consistency,\n-   exploring taxonomic composition,\n-   and visualizing global similarities between samples.\n\nThese exploratory analyses help detect potential issues in the dataset and provide an overview of the microbial communities before more advanced statistical analyses.\n\n## User Input\n\nIn this section, users can load their own dataset.\\\n\\\nThe workflow expects:\\\n- an OTU abundance table,\\\n- a taxonomy table,\\\n- and a sample metadata table.\\\n\\\nAll three tables are stored in an Excel file and imported separately using their sheet names. You can replace the file path and sheet names below with your own dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load your dataset into file_path\nfile_path <- \"../data/dataset_MISO_project.xlsx\" \n\n#Write the name of your variables\notu_sheet <- \"OTU_table\" \ntax_sheet <- \"Taxonomy\" \nsample_sheet <- \"Sample_data\" \n```\n:::\n\n\n## Load Data\n\nThe imported tables are converted into a \\`phyloseq\\` object. \\`phyloseq\\` is a R package for microbiome analysis that allows abundance data, taxonomy, and sample metadata to be stored together in a single structured object.\n\nThis makes it easier to perform analyses and visualize the microbial data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\notu_mat <- read_excel(file_path, sheet = otu_sheet)\ntax_mat <- read_excel(file_path, sheet = tax_sheet)\nsamples_df <- read_excel(file_path, sheet = sample_sheet)\n\n# Convert data frames to matrices and set row names. Phyloseq objects need to have row.names\notu_mat <- otu_mat %>%\n  tibble::column_to_rownames(\"OTU_ID\") \ntax_mat <- tax_mat %>% \n  tibble::column_to_rownames(\"Tax_ID\")\nsamples_df <- samples_df %>% \n  tibble::column_to_rownames(\"Sample_ID\")\n\n#Transform into matrixes otu and tax tables (sample table can be left as data frame)\notu_mat <- as.matrix(otu_mat)\ntax_mat <- as.matrix(tax_mat)\n\n# Transform to phyloseq objects\nOTU = otu_table(otu_mat, taxa_are_rows = TRUE)\nTAX = tax_table(tax_mat)\nsamples = sample_data(samples_df)\n\nmetagenomics <- phyloseq(OTU, TAX, samples)\n\n#sample_names(metagenomics)\n#rank_names(metagenomics)\n#sample_variables(metagenomics)\n\ntotal = median(sample_sums(metagenomics))\n# standf = function(x, t=total) round(t * (x / sum(x)))\n# metagenomics = transform_sample_counts(metagenomics, standf)\n```\n:::\n\n\n## Statistical summary\n\nA first summary of the dataset provides general information about:\\\n- the number of samples,\\\n- the number of taxa,\\\n- sequencing depth,\\\n- and metadata variables available for analysis.\\\n\\\nThis helps verify that the dataset was imported correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(metagenomics)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Length    Class     Mode \n       1 phyloseq       S4 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(otu_mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n:::\n\n\nWe can verify that the OTU table is stored as a numeric matrix of type \\`double\\`, meaning the abundance values are represented as decimal numbers.\n\nWe also checked whether some samples contained only zero values. Such samples can be problematic because they do not contain any detected microbial signal and may affect analyses, if they do exist, we should consider ignoring those samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhich(colSums(otu_mat != 0) == 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnamed integer(0)\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(colSums(otu_mat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  101.8   199.1   199.9   198.2   200.0   200.0 \n```\n\n\n:::\n:::\n\n\nNo sample composed only of zeroes was found.\n\n## Missing values check\n\nMissing values can bias analyses and lead to incorrect statistical results.\\\n\\\nWe therefore verify that the OTU table, taxonomy table, and sample metadata do not contain missing entries before continuing the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for missing values\nsum(is.na(otu_mat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(tax_mat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(samples_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n#visualize missingness\ncolSums(is.na(samples_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         dataset_name              bodysite               disease \n                    0                     0                     0 \n                  age                gender               country \n                    0                     0                     0 \nsequencing_technology              pubmedid \n                    0                     0 \n```\n\n\n:::\n:::\n\n\nWe can see that there is no missing values.\n\n## Distribution of Sequencing Depth.\n\nSequencing depth corresponds to the total number of reads obtained for each sample.\\\n\\\nLarge differences in sequencing depth may introduce technical bias in diversity analyses. Samples with extremely low read counts are sometimes removed because they may not accurately represent the microbial community.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_depth <- sample_sums(metagenomics)\n\nsummary(sample_depth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  50.91   99.57   99.94   99.09  100.00  100.00 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(depth = sample_depth), aes(x = depth)) +\n  geom_histogram(bins = 30) +\n  theme_minimal() +\n  labs(title = \"Distribution of Sequencing Depth\",\n       x = \"Reads per sample\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nSequencing depth across samples is fairly consistent, with most samples summing to approximately 100, indicating that the dataset had been normalized to relative abundances.\n\nHowever, we can notice one potential outlier, a sample exhibiting a lower total (50.91), let's try to identify it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_sums(metagenomics)[sample_sums(metagenomics) < 90]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample_2148 Sample_2280 Sample_2516 Sample_3079 Sample_3482 Sample_3493 \n   89.41782    84.62723    86.69817    89.79545    50.90540    85.95933 \nSample_3504 Sample_3519 Sample_3526 Sample_3553 Sample_3594 \n   88.59328    84.47117    88.53511    87.91809    89.17386 \n```\n\n\n:::\n:::\n\n\nMost samples show similar sequencing depth values, suggesting that the dataset was already normalized before analysis.\\\n\\\nOne sample (\\`Sample_3482\\`) exhibits a lower sequencing depth than the others. However, since the difference remains moderate, the sample was retained for the study.\n\n## Taxonomic composition\n\nTaxonomic composition plots allow visualization of the relative abundance of microbial groups across samples.\n\nThese representations help identify dominant bacterial taxa and observe potential differences between disease groups or other metadata categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetagenomics_phylum <- tax_glom(metagenomics, taxrank = \"Phylum\")\nmetagenomics_phylum_per <- transform_sample_counts(metagenomics_phylum, function(x) x / sum(x))\nplot_bar(metagenomics_phylum_per, fill = \"Phylum\") +\n  geom_bar(stat = \"identity\") +\n  theme_minimal() +\n  labs(title = \"Taxonomic composition at Phylum level\") +\n  theme(axis.text.x = element_text(angle = 90, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\nℹ Please use tidy evaluation idioms with `aes()`.\nℹ See also `vignette(\"ggplot2-in-packages\")` for more information.\nℹ The deprecated feature was likely used in the phyloseq package.\n  Please report the issue at <https://github.com/joey711/phyloseq/issues>.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_bar(metagenomics_phylum_per, x = \"disease\", fill = \"Phylum\") +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  theme_minimal() +\n  labs(title = \"Phylum composition by disease group\")\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nTo improve readability, only the 10 most abundant genera were retained in the following visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetagenomics_genus <- tax_glom(metagenomics, taxrank = \"Genus\")\n\nmetagenomics_genus_per <- transform_sample_counts(metagenomics_genus, function(x) x / sum(x))\n\n# keep top 10 genera to avoid clutter\ntop_genera <- names(sort(taxa_sums(metagenomics_genus_per), decreasing = TRUE))[1:10]\nmetagenomics_genus_top <- prune_taxa(top_genera, metagenomics_genus_per)\n\nplot_bar(metagenomics_genus_top, x = \"disease\", fill = \"Genus\") +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  theme_minimal() +\n  labs(title = \"Top 10 Genera Composition by Disease\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Beta Diversity - PCoA\n\nBeta diversity measures differences in microbial composition between samples.\\\nBray-Curtis distance is a statistic used to quantify the dissimilarity in composition between samples, based on abundance data. \n\nWe then visualise sample similarities via Principal Coordinate Analysis (PCoA). Samples positioned close together have more similar microbial compositions, whereas distant samples are more dissimilar.\n\nFirstly, we do a PCoA by gender.\n\n## Beta Diversity - PCoA by gender\n\nThis visualization allows us to explore whether microbial communities tend to cluster according to gender.\n\nStrong separation between groups would suggest that gender may influence microbiome composition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcoa <- ordinate(metagenomics, method = \"PCoA\", distance = \"bray\")\n\nplot_ordination(metagenomics, pcoa, color = \"gender\") +\n  geom_point(size = 3) +\n  theme_minimal() +\n  labs(title = \"PCoA - Bray-Curtis by gender\")\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nOverall, the plot does not show a clear separation between male and female samples.\n\nSamples from both genders largely overlap, suggesting that gender alone may not strongly influence the overall microbial community composition in this dataset.\n\nHowever, a few local clusters and dispersion differences can still be observed. Male samples appear slightly more spread out, which could indicate greater variability in microbial composition between individuals.\n\nThe first two principal coordinates explain 11.1% and 9.9% of the total variation respectively, meaning that only a portion of the microbiome variability is represented in this plot.\n\nLet's do a PCoA by gender and disease to furthermore evaluate the dataset. Adding disease status as a variable allows visualization of two metadata variables simultaneously and may reveal certain paterns.\n\n## Beta Diversity - PCoA by gender and disease\n\nThis PCoA visualization combines both gender and disease information to explore whether microbial composition varies between groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcoagd <- ordinate(metagenomics, method = \"PCoA\", distance = \"bray\")\n\nplot_ordination(metagenomics, pcoagd, color = \"gender\", shape = \"disease\") +\n  geom_point(size = 3) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nSome disease-specific clustering patterns can be observed. Samples associated with cirrhosis tend to be located more frequently in the lower part of the plot, whereas cancer samples appear more concentrated in the upper central region.\n\nIn contrast, ulcerative colitis and type 2 diabetes samples show overlap with the other groups, suggesting less distinct microbial separation.\n\nGender does not appear to create a strong separation within disease groups, as male and female samples remain mostly intermixed through the space.\n\nOverall, disease status may contribute more strongly than gender to differences in microbial composition, although the overlap between groups indicates that these effects are moderate.\n\n## Distribution of samples by gender\n\nLet's analyze the distribution of samples by gender. Strong imbalance between groups may influence statistical interpretation and reduce the reliability of comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeta_df <- data.frame(sample_data(metagenomics))\n\ngender_counts <- meta_df %>%\n  group_by(gender) %>%\n  summarise(Count = n()) %>%\n  mutate(Percentage = Count / sum(Count) * 100)\nprint(gender_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  gender Count Percentage\n  <chr>  <int>      <dbl>\n1 female   217       44.8\n2 male     267       55.2\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeta_df <- data.frame(sample_data(metagenomics))\n\ngender_counts <- meta_df %>%\n  group_by(gender) %>%\n  summarise(Count = n())\n\nggplot(gender_counts, aes(x = gender, y = Count, fill = gender)) +\n  geom_bar(stat = \"identity\") +\n  theme_minimal() +\n  labs(title = \"Number of Samples by Gender\",\n       x = \"Gender\",\n       y = \"Number of Samples\")\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nWe observe that 44.8% of the samples are female and 55.2% are male, indicating a slightly higher representation of males. However, the distribution remains relatively balanced between the two groups.\n\n## Number of samples of diseases by gender\n\nNumber of samples of diseases for females:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeta_df <- data.frame(sample_data(metagenomics))\n\ndisease_counts <- meta_df %>%\n  group_by(gender, disease) %>%\n  summarise(Count = n())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by gender and disease.\nℹ Output is grouped by gender.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(gender, disease))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(disease_counts %>% filter(gender == \"female\"),\n       aes(x = disease, y = Count, fill = disease)) +\n  geom_bar(stat = \"identity\") +\n  theme_minimal() +\n  labs(title = \"Number of Female Samples per Disease\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nUlcerative colitis (IBD) has the highest number of samples with more than 75 counts, followed by type 2 diabetes (T2D), then cirrhosis, and finally cancer, which has fewer than 25 counts.\n\nNumber of samples of diseases for males:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(disease_counts %>% filter(gender == \"male\"),\n       aes(x = disease, y = Count, fill = disease)) +\n  geom_bar(stat = \"identity\") +\n  theme_minimal() +\n  labs(title = \"Number of Male Samples per Disease\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nType 2 diabetes (T2D) has the highest number of samples with more than 100 counts, followed by type cirrhosis, then Ulcerative colitis (IBD), and finally cancer, which has around 25 counts.\n\nWe can see that there are differences in the number of samples per disease, depending on gender.\n\n## Distribution of bacterial class by gender\n\nThe taxonomic composition at the class level was compared between genders using relative abundance profiles. Only the most abundant classes (top 10) were retained to improve visualization clarity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetagenomics_class <- tax_glom(metagenomics, taxrank = \"Class\")\nmetagenomics_class_per <- transform_sample_counts(metagenomics_class, function(x) x / sum(x))\ntop_classes <- names(sort(taxa_sums(metagenomics_class_per), decreasing = TRUE))[1:10]\nmetagenomics_class_top <- prune_taxa(top_classes, metagenomics_class_per)\n\nplot_bar(metagenomics_class_top, x = \"gender\", fill = \"Class\") +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  theme_minimal() +\n  labs(title = \"Bacterial TOP 10 Classes Distribution by Gender\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe same analysis but with all the bacterial classes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_bar(metagenomics_class, x = \"gender\", fill = \"Class\") +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  theme_minimal() +\n  labs(title = \"Bacterial Class Distribution by Gender\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](datapreparation_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nIt seems that the bacterial distribution is approximately the same for each gender.\n\nOverall, the data preparation step provided a clear overview of the dataset and ensured its suitability for the study. We examined key characteristics such as sample distribution across disease groups and gender, revealing a slight imbalance in both cases (more male samples than female, and varying representation across conditions).\n\nThese checks helped confirm data quality, identify potential biases, and ensure that the analyses are interpreted in the right context.\n",
    "supporting": [
      "datapreparation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}