{
  "hash": "554460731ebec23c515b212db70f8f2e",
  "result": {
    "engine": "knitr",
    "markdown": "---\n  title: \"2.2: Beta Diversity\"\n  format: \n    html: \n      toc: true\n      code-fold: true\n      code-summary: \"Show code\"\n      code-tools: true\n  editor: visual\n  categories: [\"Diversity Analysis\"]\n  image: \"/img/beta.png\"\n  description: \"Beta Diversity Analysis on Metagenomic Data\"\n---\n\n\n\n# Beta Diversity\n\nBeta diversity quantifies the dissimilarity between pairs of samples. It answers how different are the microbial communities across groups. Unlike alpha diversity (within-sample richness/diversity), beta diversity asks:“How different are microbial communities across samples or disease groups?”\n\nWe examine whether gut microbiomes differ significantly between disease groups using two distance metrics. These metrics measure the degree of dissimilarity between pairs of samples but differ in the ecological information they capture.\n\n### Bray–Curtis\n\nBray-Curtis dissimilarity is an abundance-sensitive metric that considers both the presence and relative abundance of taxa within samples. It is widely used in microbiome research because it emphasizes compositional differences driven by changes in dominant organisms. Values range from 0 to 1, where 0 indicates identical community composition and 1 indicates complete dissimilarity. Bray–Curtis is particularly useful for detecting shifts in microbial abundance associated with disease or environmental factors.\n\n$$\nBC = \\frac{\\sum_{i=1}^{n} |p^a_{i} - p^b_{i}|}{\\sum_{i=1}^{n} (p^a_{i} + p^b_{i})}\n$$\n\n$n$ = total number of species\n\n$p^a_{i}$ and $p^b_{i}$ = are the relative abundance of species $i$ in samples $a$ and $b$\n\n### **Jaccard**\n\nJaccard distance is a presence–absence based metric that measures differences in taxonomic membership independently of abundance. It evaluates whether the same taxa are shared between samples and is therefore sensitive to taxon turnover rather than abundance variation. This metric is useful for identifying whether disease-associated microbial changes reflect the loss or gain of taxa rather than changes in relative abundance.\n\n$$\nJ(A,B)=1-\\frac{A\\cup B}{A\\cap B}\n$$\n\nwhere $A$ and $B$ represent the sets of taxa present in two samples.\n\nUsing both Bray–Curtis and Jaccard metrics provides complementary ecological perspectives on microbial community structure. Bray–Curtis captures abundance-driven compositional changes, whereas Jaccard focuses on differences in taxon presence and absence. Together, these approaches allow a more comprehensive assessment of microbiome variation across disease groups.\n\n## Ordination\n\n### Distance Matrices\n\nWe first compute distance matrices from relative abundance for each beta diversity metric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bray-Curtis (abundance‑sensitive)\ndist_bray <- distance(metagenomics, method = \"bray\")\n\n# Jaccard (presence/absence only)\ndist_jaccard <- distance(metagenomics, method = \"jaccard\")\n```\n:::\n\n\n### **Principal Correspondence Analysis (PCoA)**\n\nThis method is also known as MDS (Metric Multidimensional Scaling). PCoA provides Euclidean representation of a set of objects whose relationship is measured by any dissimilarity index. This projects the high‑dimensional distance matrix into two dimensions, allowing us to visualize how samples cluster by disease status.\n\n::: panel-tabset\n### Bray-Curtis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nord_bray <- ordinate(metagenomics, method = \"MDS\", distance = dist_bray)\n\n# For MDS/PCoA, the ordination object contains eigenvalues\nvar_exp <- round(ord_bray$values$Eigenvalues / sum(ord_bray$values$Eigenvalues) * 100, 1)\n\np_bray <- plot_ordination(metagenomics, ord_bray, color = \"disease\", shape = \"disease\") +\n  geom_point(size = 3, alpha = 0.8) +\n  stat_ellipse(aes(group = disease), linetype = 2, level = 0.95) +\n  ggtitle(\"Bray-Curtis Dissimilarity\") +\n  labs(x = paste0(\"PCoA1 (\", var_exp[1], \"%)\"), \n       y = paste0(\"PCoA2 (\", var_exp[2], \"%)\")) +\n  theme(legend.position = \"bottom\")\n\np_bray\n```\n\n::: {.cell-output-display}\n![](beta_diversity_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggsave(here(\"figures\", \"Beta\", \"pcoa_bray.pdf\"), p_bray)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSaving 7 x 5 in image\n```\n\n\n:::\n:::\n\n\nSamples clustering closely together have more similar microbial compositions. Separation between disease groups suggests differences in microbial community structure associated with disease status.\n\n### Jaccard\n\n\n::: {.cell}\n\n```{.r .cell-code}\nord_jaccard <- ordinate(metagenomics, method = \"MDS\", distance = dist_jaccard)\n\n# For MDS/PCoA, the ordination object contains eigenvalues\nvar_exp <- round(ord_jaccard$values$Eigenvalues / sum(ord_jaccard$values$Eigenvalues) * 100, 1)\n\np_jaccard <- plot_ordination(metagenomics, ord_jaccard, color = \"disease\", shape = \"disease\") +\n  geom_point(size = 3, alpha = 0.8) +\n  stat_ellipse(aes(group = disease), linetype = 2, level = 0.95) +\n  ggtitle(\"Jaccard Dissimilarity\") +\n  labs(x = paste0(\"PCoA1 (\", var_exp[1], \"%)\"), \n       y = paste0(\"PCoA2 (\", var_exp[2], \"%)\")) +\n  theme(legend.position = \"bottom\")\n\np_jaccard\n```\n\n::: {.cell-output-display}\n![](beta_diversity_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggsave(here(\"figures\", \"Beta\", \"pcoa_jaccard.pdf\"), p_jaccard)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSaving 7 x 5 in image\n```\n\n\n:::\n:::\n\n\nJaccard ordination visualizes differences in taxon membership independent of abundance. Group separation indicates disease-associated changes in which taxa are present rather than their relative abundance.\n\n### Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_bray_jaccard <- p_bray | p_jaccard\ncombined_bray_jaccard\n```\n\n::: {.cell-output-display}\n![](beta_diversity_files/figure-html/combined-bray-jaccard-1.png){width=1440}\n:::\n\n```{.r .cell-code}\nggsave(here(\"figures\", \"Beta\", \"combined_bray_jaccard.pdf\"), combined_bray_jaccard)\n```\n:::\n\n:::\n\n## PERMANOVA\n\n### Checking Assumption: Homogeneity of Multivariate Dispersion\n\nWe want to use PERMANOVA on both beta diversity metrics but it is sensitive to differences in within‑group dispersion (variance). We test this using `betadisper()` (multivariate analogue of Levene’s test).\n\nWe performed **`betadisper()`** on both Bray‑Curtis and Jaccard distance matrices, followed by a permutation test. The test evaluates whether the within‑group dispersion (variance around the group median) differs significantly among the four disease groups.\n\n::: panel-tabset\n#### Bray dispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisp_bray <- betadisper(dist_bray, samples_df$disease)\n# pdf(\"figures/Beta/boxplot_betaDisperson_bray.pdf\")\nboxplot(disp_bray, col = viridis(4, option = \"cividis\"), main = \"Bray-Curtis dispersion per diseases\")\n```\n\n::: {.cell-output-display}\n![](beta_diversity_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Permutation test for homogeneity\ndisp_test_bray <- permutest(disp_bray, permutations = 999)\ndisp_test_bray\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n           Df  Sum Sq  Mean Sq      F N.Perm Pr(>F)    \nGroups      3 0.29385 0.097948 18.158    999  0.001 ***\nResiduals 480 2.58921 0.005394                         \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n#### Jaccard dispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisp_jaccard <- betadisper(dist_jaccard, samples_df$disease)\nboxplot(disp_jaccard, col = viridis(4, option = \"cividis\"), main = \"Jaccard dispersion per diseases\")\n```\n\n::: {.cell-output-display}\n![](beta_diversity_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndisp_test_jaccard <- permutest(disp_jaccard, permutations = 999)\ndisp_test_jaccard\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n           Df  Sum Sq  Mean Sq      F N.Perm Pr(>F)    \nGroups      3 0.12773 0.042578 18.513    999  0.001 ***\nResiduals 480 1.10393 0.002300                         \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\nBoth tests are highly significant (p \\< 0.001), meaning: Only 1 out of 1000 permutations produced an F‑statistic as extreme as the one observed.\n\nThis is very strong evidence that the groups do NOT have equal multivariate dispersions. In other words, the within-group variability (how scattered samples are) is not equal across diseases. The assumption of homogeneity of variances is violated for both distance metrics.\n\n### Pairwise Dispersion\n\nTo identify which disease groups differed in multivariate dispersion, we performed pairwise comparisons using the `betadisper` function with 999 permutations.\n\n::: panel-tabset\n#### Bray\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pairwise comparisons\ndisp_bray <- betadisper(dist_bray, samples_df$disease)\npairwise_bray <- permutest(disp_bray, pairwise = TRUE, permutations = 999)\npairwise_bray\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n           Df  Sum Sq  Mean Sq      F N.Perm Pr(>F)    \nGroups      3 0.29385 0.097948 18.158    999  0.001 ***\nResiduals 480 2.58921 0.005394                         \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nPairwise comparisons:\n(Observed p-value below diagonal, permuted p-value above diagonal)\n                           cancer  cirrhosis ibd_ulcerative_colitis   t2d\ncancer                            1.9900e-01             1.6000e-02 0.029\ncirrhosis              1.8713e-01                        1.0000e-03 0.287\nibd_ulcerative_colitis 1.3615e-02 2.4127e-07                        0.001\nt2d                    3.0887e-02 3.0252e-01             1.4536e-11      \n```\n\n\n:::\n:::\n\n\nThe IBD group has significantly different dispersion from all other three groups (cancer, cirrhosis, T2D). In contrast, cancer, cirrhosis, and T2D do not differ from each other (except cancer vs T2D is borderline significant at 0.031 – still significant, but weaker).\n\n#### Jaccard\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisp_jaccard <- betadisper(dist_jaccard, samples_df$disease)\npairwise_jaccard <- permutest(disp_jaccard, pairwise = TRUE, permutations = 999)\npairwise_jaccard\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n           Df  Sum Sq  Mean Sq      F N.Perm Pr(>F)    \nGroups      3 0.12773 0.042578 18.513    999  0.001 ***\nResiduals 480 1.10393 0.002300                         \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nPairwise comparisons:\n(Observed p-value below diagonal, permuted p-value above diagonal)\n                           cancer  cirrhosis ibd_ulcerative_colitis   t2d\ncancer                            2.2600e-01             1.0000e-02 0.020\ncirrhosis              2.1996e-01                        1.0000e-03 0.203\nibd_ulcerative_colitis 1.4762e-02 6.1841e-07                        0.001\nt2d                    2.1386e-02 1.9695e-01             5.0089e-12      \n```\n\n\n:::\n:::\n\n\nIBD differs significantly from all others (p \\< 0.02 for each). Cancer vs cirrhosis not significant (p = 0.21), cirrhosis vs T2D not significant (p = 0.196). Cancer vs T2D is significant (p = 0.02). The conclusion is the same for Bray, IBD is the main outlier in terms of dispersion.\n:::\n\nPairwise comparisons revealed that the IBD group had significantly different multivariate dispersion compared to all other diseases (p \\< 0.05 for all comparisons), while dispersions among cancer, cirrhosis, and type 2 diabetes were largely similar (p \\> 0.05 except cancer vs T2D). This indicates that the overall heterogeneity in dispersion is primarily attributable to the IBD group.\n\n### PERMANOVA\n\nPERMANOVA (adonis2) is used to test whether the centroids of the groups (disease status) are significantly different in the multivariate space defined by the distance metrics. When dispersions are unequal, a significant PERMANOVA p-value may reflect dispersion differences rather than true centroid differences.\n\n::: panel-tabset\n#### PERMANOVA Bray\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermanova_bray <- adonis2(dist_bray ~ disease, \n                          data = samples_df, \n                          permutations = 999)\nprint(permanova_bray)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = dist_bray ~ disease, data = samples_df, permutations = 999)\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      3   13.545 0.08694 15.235  0.001 ***\nResidual 480  142.253 0.91306                  \nTotal    483  155.798 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n-   Disease explains 8.7% of the total variation in community composition (abundance‑sensitive).\n\n-   Residual (unexplained) = 91.3%.\n\n-   F = 15.2 – large relative to null permutations.\n\n-   p = 0.001 – significant\n\n#### PERMANOVA Jaccard\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermanova_jaccard <- adonis2(dist_jaccard ~ disease, \n                             data = samples_df, \n                             permutations = 999)\nprint(permanova_jaccard)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = dist_jaccard ~ disease, data = samples_df, permutations = 999)\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      3   10.497 0.05553 9.4077  0.001 ***\nResidual 480  178.528 0.94447                  \nTotal    483  189.025 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n-   Disease explains 5.6% of variation (presence/absence only).\n\n-   Residuals = 94.4%\n\n-   F = 9.4 – also large.\n\n-   p = 0.001 – significant.\n:::\n\nBoth metrics show a statistically significant association between disease status and microbial community dissimilarity. The effect sizes (R²) are small. Bray‑Curtis explains more variation than Jaccard (8.7% vs 5.6%), suggesting that abundance differences are more discriminative than just presence/absence.\n\nBoth PERMANOVA and beta dispersion tests were significant (p = 0.001 for both Bray‑Curtis and Jaccard). This indicates that disease status is associated with differences in both the average microbial community composition and the within‑group variability.\n\n### Pairwise PERMANOVA\n\nPairwise PERMANOVA is a post‑hoc test used after a significant PERMANOVA (which tells you “at least one group differs”). It performs separate PERMANOVA tests on each combination of two groups (e.g., cancer vs cirrhosis, cancer vs IBD, etc.) to determine which specific pairs of groups are significantly different from each other.\n\n::: panel-tabset\n#### Bray\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.adonis2(dist_bray ~ disease, data = samples_df, nperm = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$parent_call\n[1] \"dist_bray ~ disease , strata = Null , permutations 999\"\n\n$ibd_ulcerative_colitis_vs_cirrhosis\n          Df SumOfSqs      R2     F Pr(>F)    \nModel      1    8.439 0.10189 29.95  0.001 ***\nResidual 264   74.385 0.89811                 \nTotal    265   82.824 1.00000                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$ibd_ulcerative_colitis_vs_t2d\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    6.190 0.06307 21.272  0.001 ***\nResidual 316   91.961 0.93693                  \nTotal    317   98.151 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$ibd_ulcerative_colitis_vs_cancer\n          Df SumOfSqs      R2     F Pr(>F)    \nModel      1    1.401 0.02622 5.224  0.001 ***\nResidual 194   52.019 0.97378                 \nTotal    195   53.419 1.00000                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$cirrhosis_vs_t2d\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    3.473 0.03707 11.009  0.001 ***\nResidual 286   90.234 0.96293                  \nTotal    287   93.708 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$cirrhosis_vs_cancer\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    3.811 0.07044 12.428  0.001 ***\nResidual 164   50.292 0.92956                  \nTotal    165   54.103 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$t2d_vs_cancer\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    1.995 0.02855 6.3486  0.001 ***\nResidual 216   67.867 0.97145                  \nTotal    217   69.862 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nattr(,\"class\")\n[1] \"pwadstrata\" \"list\"      \n```\n\n\n:::\n:::\n\n\n#### Jaccard\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.adonis2(dist_jaccard ~ disease, data = samples_df, nperm = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$parent_call\n[1] \"dist_jaccard ~ disease , strata = Null , permutations 999\"\n\n$ibd_ulcerative_colitis_vs_cirrhosis\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    6.357 0.06261 17.633  0.001 ***\nResidual 264   95.182 0.93739                  \nTotal    265  101.539 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$ibd_ulcerative_colitis_vs_t2d\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    4.863 0.04015 13.217  0.001 ***\nResidual 316  116.271 0.95985                  \nTotal    317  121.134 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$ibd_ulcerative_colitis_vs_cancer\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    1.247 0.01798 3.5525  0.001 ***\nResidual 194   68.108 0.98202                  \nTotal    195   69.356 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$cirrhosis_vs_t2d\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1     2.65 0.02344 6.8636  0.001 ***\nResidual 286   110.42 0.97656                  \nTotal    287   113.07 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$cirrhosis_vs_cancer\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    2.894 0.04442 7.6238  0.001 ***\nResidual 164   62.257 0.95558                  \nTotal    165   65.151 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$t2d_vs_cancer\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      1    1.629 0.01917 4.2207  0.001 ***\nResidual 216   83.346 0.98083                  \nTotal    217   84.974 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nattr(,\"class\")\n[1] \"pwadstrata\" \"list\"      \n```\n\n\n:::\n:::\n\n:::\n\nPairwise PERMANOVA (999 permutations) revealed that all disease groups were significantly different from each other for both Bray‑Curtis (p = 0.001 for all comparisons) and Jaccard (p = 0.001 for all comparisons) distances. However, because the PERMDISP test showed heterogeneous multivariate dispersions (driven primarily by the IBD group), the significant pairwise PERMANOVA results may reflect a combination of differences in both centroid location and within‑group dispersion.\n\n## Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table\nlibrary(knitr)\n\nresults_df <- data.frame(\n  Metric = c(\"Bray-Curtis\", \"Jaccard\"),\n  R2 = c(round(permanova_bray$R2[1], 3), round(permanova_jaccard$R2[1], 3)),\n  F = c(round(permanova_bray$F[1], 2), round(permanova_jaccard$F[1], 2)),\n  `p-value` = c(format(permanova_bray$`Pr(>F)`[1], digits = 4),\n                format(permanova_jaccard$`Pr(>F)`[1], digits = 4)),\n  `Dispersion p-value` = c(format(disp_test_bray$tab$`Pr(>F)`[1], digits = 4),\n                           format(disp_test_jaccard$tab$`Pr(>F)`[1], digits = 4))\n)\n\nkable(results_df, caption = \"PERMANOVA and beta dispersion test results\")\n```\n\n::: {.cell-output-display}\n\n\nTable: PERMANOVA and beta dispersion test results\n\n|Metric      |    R2|     F|p.value |Dispersion.p.value |\n|:-----------|-----:|-----:|:-------|:------------------|\n|Bray-Curtis | 0.087| 15.23|0.001   |0.001              |\n|Jaccard     | 0.056|  9.41|0.001   |0.001              |\n\n\n:::\n:::\n\n\nThe table summarizes:\n\n-   effect size (R²)\n\n-   PERMANOVA significance\n\n-   homogeneity of dispersion testing\n\nHigher R² values indicate stronger disease-associated microbial differences.\n\n## Conclusion\n\nBeta diversity was assessed using Bray–Curtis and Jaccard distance metrics. Principal Coordinate Analysis (PCoA) was used to visualize microbial community differences between disease groups. Group differences were evaluated using PERMANOVA (`adonis2`, 999 permutations). A key assumption of PERMANOVA is homogeneity of multivariate dispersions. We check this with a beta dispersion test. Homogeneity of multivariate dispersion was assessed using `betadisper()` followed by permutation testing. Pairwise dispersion testing and pairwise PERMANOVA were evaluated to identify which disease groups differed in dispersion.\n\nBeta diversity analysis revealed significant differences in microbial community composition between disease groups.\n\n-   Bray–Curtis explained more variation than Jaccard, suggesting that abundance shifts contributed more strongly than simple taxon presence/absence.\n\n-   Significant PERMANOVA results indicate disease-associated differences in microbiome composition.\n\n-   Significant beta dispersion tests indicate unequal within-group variability, primarily due to the IBD group differing in variance from the others.\n\nNevertheless, the consistent pairwise PERMANOVA results suggest true differences in community composition across diseases.\n\n\n\n# Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info(pkgs = \"attached\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.6.0 (2026-04-24)\n os       macOS Tahoe 26.4\n system   aarch64, darwin23\n ui       X11\n language (EN)\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Europe/Paris\n date     2026-05-24\n pandoc   3.9.0.2 @ /opt/homebrew/bin/ (via rmarkdown)\n quarto   1.8.27 @ /usr/local/bin/quarto\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package        * version date (UTC) lib source\n broom          * 1.0.13  2026-05-14 [1] CRAN (R 4.6.0)\n cluster        * 2.1.8.2 2026-02-05 [1] CRAN (R 4.6.0)\n dplyr          * 1.2.1   2026-04-03 [1] CRAN (R 4.6.0)\n forcats        * 1.0.1   2025-09-25 [1] CRAN (R 4.6.0)\n FSA            * 0.10.1  2026-01-10 [1] CRAN (R 4.6.0)\n ggplot2        * 4.0.3   2026-04-22 [1] CRAN (R 4.6.0)\n gridExtra      * 2.3     2017-09-09 [1] CRAN (R 4.6.0)\n here           * 1.0.2   2025-09-15 [1] CRAN (R 4.6.0)\n igraph         * 2.3.1   2026-05-04 [1] CRAN (R 4.6.0)\n knitr          * 1.51    2025-12-20 [1] CRAN (R 4.6.0)\n lubridate      * 1.9.5   2026-02-04 [1] CRAN (R 4.6.0)\n pairwiseAdonis * 0.4.1   2026-05-24 [1] Github (pmartinezarbizu/pairwiseAdonis@cb190f7)\n patchwork      * 1.3.2   2025-08-25 [1] CRAN (R 4.6.0)\n permute        * 0.9-10  2026-02-06 [1] CRAN (R 4.6.0)\n phyloseq       * 1.56.0  2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n purrr          * 1.2.2   2026-04-10 [1] CRAN (R 4.6.0)\n readr          * 2.2.0   2026-02-19 [1] CRAN (R 4.6.0)\n readxl         * 1.5.0   2026-05-16 [1] CRAN (R 4.6.0)\n SpiecEasi      * 2.0.0   2026-04-28 [1] Bioconductor 3.23 (R 4.6.0)\n stringr        * 1.6.0   2025-11-04 [1] CRAN (R 4.6.0)\n tibble         * 3.3.1   2026-01-11 [1] CRAN (R 4.6.0)\n tidyr          * 1.3.2   2025-12-19 [1] CRAN (R 4.6.0)\n tidyverse      * 2.0.0   2023-02-22 [1] CRAN (R 4.6.0)\n vegan          * 2.7-3   2026-03-04 [1] CRAN (R 4.6.0)\n viridis        * 0.6.5   2024-01-29 [1] CRAN (R 4.6.0)\n viridisLite    * 0.4.3   2026-02-04 [1] CRAN (R 4.6.0)\n\n [1] /Library/Frameworks/R.framework/Versions/4.6/Resources/library\n * ── Packages attached to the search path.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "beta_diversity_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}