---
title: "Data organizing and preliminary analysis"
format: html
editor: visual
execute:
  echo: true
---

## Create phyloseq object

```{r}
#| label: data object
#| include: true
# import necessary libraries
library("phyloseq")
library("ggplot2")      # graphics
library("readxl")       # necessary to import the data from Excel file
library("dplyr")        # filter and reformat data frames
library("tibble")       # Needed for converting column to row names
library("readxl")       # read excel files

setwd(dirname(getwd()))

otu_mat<- read_excel("data/dataset_MISO_project.xlsx", sheet = "OTU_table")
tax_mat<- read_excel("data/dataset_MISO_project.xlsx", sheet = "Taxonomy")
samples_df <- read_excel("data/dataset_MISO_project.xlsx", sheet = "Sample_data")

# Convert data frames to matrices and set row names. Phyloseq objects need to have row.names
otu_mat <- otu_mat %>%
  tibble::column_to_rownames("OTU_ID")
tax_mat <- tax_mat %>%
  tibble::column_to_rownames("Tax_ID")
samples_df <- samples_df %>% 
  tibble::column_to_rownames("Sample_ID")

#Transform into matrixes otu and tax tables (sample table can be left as data frame)
otu_mat <- as.matrix(otu_mat)
tax_mat <- as.matrix(tax_mat)

# Transform to phyloseq objects
OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(samples_df)

metagenomics <- phyloseq(OTU, TAX, samples)
metagenomics
```

## Check data

```{r}
#| label: data visualization
#| include: true
sample_names(metagenomics)
rank_names(metagenomics)
sample_variables(metagenomics)

dir.create("figures", showWarnings = FALSE)
dir.create("figures/Preliminary", showWarnings = FALSE, recursive = TRUE)

```

Visualize data

```{r}
# sample_totals <- sample_sums(metagenomics)
# p6 <- boxplot(sample_totals, main = "Sample Sizes", ylab = "Sum of Relative Abundance", col = "lightblue")
# p6
# ggsave("figures/Preliminary/bar_graph_sample_sums.pdf", p6)

sample_totals <- sample_sums(metagenomics)

# Create data frame for ggplot
df_sample_totals <- data.frame(Total_reads = sample_totals)

p6 <- ggplot(df_sample_totals, aes(y = Total_reads)) +
  geom_boxplot(fill = "lightblue", color = "black") +
  labs(title = "Sample Sizes", y = "Sample Totals") +
  theme_minimal()

# Save with ggsave
ggsave("figures/Preliminary/boxplot_sample_sums.pdf", p6)
```

## Bar Plots by Sample Data

```{r}
#| label: Bar Plot of bacteria class distribution by sample data
#| include: true

country <- samples_df$country
country_count <- table(country)
# Convert the table to a data frame for ggplot
country_df <- as.data.frame(country_count)
colnames(country_df) <- c("country", "count")

p1 <- ggplot(country_df, aes(x = country, y = count)) +
  geom_col(fill = "blue") +
  labs(title = "Sample count by country", x = "country", y = "sample count")
p1
ggsave("figures/Preliminary/barplot_sample_count_country.pdf", p1)

disease <- samples_df$disease
disease_count <- table(disease)
# Convert the table to a data frame for ggplot
disease_df <- as.data.frame(disease_count)
colnames(disease_df) <- c("disease", "count")
p9 <- ggplot(disease_df, aes(x = disease, y = count)) +
  geom_col(fill = "blue") +
  labs(title = "Sample count by disease", x = "disease", y = "sample count")
p9
ggsave("figures/Preliminary/barplot_sample_count_disease.pdf", p9)

metagenomics_disease <- merge_samples(metagenomics, "disease")
p2 <- plot_bar(metagenomics_disease, fill = "Class") + 
geom_bar(aes(color=Class, fill=Class), stat="identity", position="stack") + 
  labs(
      title = "Bacteria class distribution by diseases",
      x = "Disease",
      y = "Abundance",
    )
p2
# save plots in a folder 
ggsave("figures/Preliminary/bar_graph_disease_Class.pdf", p2)

metagenomics_country <- merge_samples(metagenomics, "country")
p3 <- plot_bar(metagenomics_country, fill = "Class") + 
geom_bar(aes(color=Class, fill=Class), stat="identity", position="stack") + 
  labs(
      title = "Bacteria class distribution by country",
      x = "Country",
      y = "Abundance",
    )
p3
ggsave("figures/Preliminary/bar_graph_country_Class.pdf", p3)

metagenomics_gender <- merge_samples(metagenomics, "gender")
p4 <- plot_bar(metagenomics_gender, fill = "Class") + 
geom_bar(aes(color=Class, fill=Class), stat="identity", position="stack") + 
  labs(
      title = "Bacteria class distribution by gender",
      x = "Gender",
      y = "Abundance",
    )
p4
ggsave("figures/Preliminary/bar_graph_gender_Class.pdf", p4)


# Count occurrences per country and disease
counts <- samples_df %>%
  count(country, disease)   # handles NA by default (drops them)

p5 <- ggplot(counts, aes(x = country, y = n, fill = disease)) +
  geom_col(position = "stack") +            # stacked bars
  labs(title = "Disease counts by country",
       x = "Country",
       y = "Number of samples",
       fill = "Disease") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p5
# Save the plot
ggsave("figures/Preliminary/disease_counts_by_country.pdf", p5)

```

# **Taxnomic barplot**

```{r}
p7 <- plot_bar(metagenomics, fill = "Phylum") + 
geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack") + 
  labs(
      title = "Bacteria distribution by Phylum",
      x = "Samples",
      y = "Abundance",
    )
p7
ggsave("figures/Preliminary/bar_graph_Phylum.pdf", p7)

# p8 <- plot_bar(metagenomics, fill = "Class") + 
# geom_bar(aes(color=Class, fill=Class), stat="identity", position="stack") + 
#   labs(
#       title = "Bacteria distribution by Class",
#       x = "Samples",
#       y = "Abundance",
#     )
# p8
# ggsave("figures/Preliminary/bar_graph_Class.pdf", p8)
```
