---
title: "Preliminary work for the Statistical Analysis of Metagenomic Data"
format: html
editor: visual
---

```{r}

#| label: load-packages
#| include: false

library("phyloseq")
library("ggplot2")      # graphics
library("readxl")       # necessary to import the data from Excel file
library("dplyr")        # filter and reformat data frames
library("tibble")       # Needed for converting column to row names
```

## Data

```{#| label: load-data}
#| include: true
otu_mat<- read_excel("../data/dataset_MISO_project.xlsx", sheet = "OTU_table")
tax_mat<- read_excel("../data/dataset_MISO_project.xlsx", sheet = "Taxonomy")
samples_df <- read_excel("../data/dataset_MISO_project.xlsx", sheet = "Sample_data")

# Convert data frames to matrices and set row names. Phyloseq objects need to have row.names
otu_mat <- otu_mat %>%
  tibble::column_to_rownames("OTU_ID") 
tax_mat <- tax_mat %>% 
  tibble::column_to_rownames("Tax_ID")
samples_df <- samples_df %>% 
  tibble::column_to_rownames("Sample_ID")

#Transform into matrixes otu and tax tables (sample table can be left as data frame)
otu_mat <- as.matrix(otu_mat)
tax_mat <- as.matrix(tax_mat)

# Transform to phyloseq objects
OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(samples_df)

carbom <- phyloseq(OTU, TAX, samples)
carbom

sample_names(carbom)
rank_names(carbom)
sample_variables(carbom)

total = median(sample_sums(carbom))
# standf = function(x, t=total) round(t * (x / sum(x)))
# carbom = transform_sample_counts(carbom, standf)
```

## Statistical summary

```{r}
#| label: stats-summary
#| include: true

summary(carbom)
```

```{r}
typeof(otu_mat)
#type is double (double precision floating point numbers)

which(colSums(otu_mat != 0) == 0)
summary(colSums(otu_mat))
#there is no column of samples with only zeroes.
```

## Taxonomic composition

```{r}
carbom_phylum <- tax_glom(carbom, taxrank = "Phylum")
carbom_phylum_per <- transform_sample_counts(carbom_phylum, function(x) x / sum(x))
plot_bar(carbom_phylum_per, fill = "Phylum") +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Taxonomic composition at Phylum level") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
plot_bar(carbom_phylum_per, x = "disease", fill = "Phylum") +
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  labs(title = "Phylum composition by disease group")
```

```{r}
carbom_genus <- tax_glom(carbom, taxrank = "Genus")

carbom_genus_per <- transform_sample_counts(carbom_genus, function(x) x / sum(x))

# keep top 10 genera to avoid clutter
top_genera <- names(sort(taxa_sums(carbom_genus_per), decreasing = TRUE))[1:10]
carbom_genus_top <- prune_taxa(top_genera, carbom_genus_per)

plot_bar(carbom_genus_top, x = "disease", fill = "Genus") +
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  labs(title = "Top 10 Genera Composition by Disease") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Number of samples of diseases by gender

Females:

```{r}
meta_df <- data.frame(sample_data(carbom))

disease_counts <- meta_df %>%
  group_by(gender, disease) %>%
  summarise(Count = n())

ggplot(disease_counts %>% filter(gender == "female"),
       aes(x = disease, y = Count, fill = disease)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of Female Samples per Disease") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Males:

```{r}
ggplot(disease_counts %>% filter(gender == "male"),
       aes(x = disease, y = Count, fill = disease)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of male Samples per Disease") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
